export const REPORTS_LIST_REQUEST = "REPORTS_LIST_REQUEST";
export const REPORTS_LIST_SUCCESS = "REPORTS_LIST_SUCCESS";
export const REPORTS_LIST_FAIL = "REPORTS_LIST_FAIL";

export const REPORTS_CREATE_REQUEST = "REPORTS_CREATE_REQUEST";
export const REPORTS_CREATE_SUCCESS = "REPORTS_CREATE_SUCCESS";
export const REPORTS_CREATE_FAIL = "REPORTS_CREATE_FAIL";

export const REPORTS_UPDATE_REQUEST = "REPORTS_UPDATE_REQUEST";
export const REPORTS_UPDATE_SUCCESS = "REPORTS_UPDATE_SUCCESS";
export const REPORTS_UPDATE_FAIL = "REPORTS_UPDATE_FAIL";

export const REPORTS_DELETE_REQUEST = "REPORTS_DELETE_REQUEST";
export const REPORTS_DELETE_SUCCESS = "REPORTS_DELETE_SUCCESS";
export const REPORTS_DELETE_FAIL = "REPORTS_DELETE_FAIL";